### PR TITLE
Update to 0172 and 0173

### PR DESCRIPTION
**Pull request by Slothjams**
The icon assets for 0172 and 0173 were swapped

### CODE REVIEW

**Comment by cg5037** [comment]
@Slothjams Need to review with me and @bradleyofkansas to determine if this is a non-passive change thus making it a major release.

**Comment by mjhenkes** [comment]
It's passive from an API standpoint, if that helps.

**Comment by bradleyofkansas** [comment]
@mjhenkes So just to be sure, this will still constitute as a minor release?  Just want to make sure before I screw something.

cc @Slothjams @cg5037

**Comment by mjhenkes** [comment]
I classify it as minor due to the aliasing done in the CSV. The dischargeComingDue and dischargeOverDue aliases remain which is what we will generate our react components from. This would be non-passive if anyone was consuming the icons directly. Do you know of any consumers not using the csv aliases?

**Pull request merged**
