### PR TITLE
New Icons Added

### PR DESCRIPTION
**Pull request by Slothjams**
* New Icon Added - 0171
* Used within Cerner Care Team Assignments to indicate a patient's
discharge has been completed
* New Icon Added - 0172
* Used within Cerner Care Team Assignments to indicate a patient is
past due on their discharge
* New Icon Added - 0173
* Used within Cerner Care Team Assignments to indicate a patient's
discharge is coming due
* New Icon Added - 0174
* flipHorizontal - used within Media Gallery component to flip image
horizontally
* flipVertical - used within Media Gallery  omponent to flip image
vertically
* New Icon Added - 0175
* rotateRight - used within Media Gallery component to rotate an image
right
* rotateLeft - used within Media Gallery component o rotate an image
left

### CODE REVIEW

**Comment by Slothjams** [comment]
@bradleyofkansas Any issues with this or can it be merged?

**Comment by Slothjams** [comment]
@bradleyofkansas Saw this hadn't been committed yet, so I added a few more icons to the Pull Request. The icons are the Q4 Usability Test recommendations, as we have that Jira due date today.

**Comment by bradleyofkansas** [comment]
@Slothjams , during the review, I noticed a few issues we will need to sort out.  Per the documentation for naming under the 'mark' section of the icons naming, we should not separate the words that make up the mark. (https://wiki.ucern.com/display/UserExperience/OCS)

The icons that are breaking this are and should instead be: 
0170_bed_check_i_heavyCircleGreen.svg  >  0170_checkBed_i_heavyCircleGreen.svg
0171_doorOpen_check_i_heavyCircleGreen.svg > 0171_checkDoorOpen_i_heavyCircleGreen.svg
0172_doorOpen_exclamation_i_heavyTriangleRed.svg > 0172_exclamationDoorOpen_i_heavyTriangleRed.svg
0173_doorOpen_exclamation_i_heavyTriangleYellow.svg > 0173_exclamationDoorOpen_i_heavyTriangleYello.svg

**Comment by Slothjams** [comment]
@bradleyofkansas  Just made those updates

**Comment by bradleyofkansas** [comment]
@Slothjams  During the review of the assets, I noticed that 0172 and 0173 are aligned with the artboard differently  Please take a look and let me know if you see it too.

**Comment by bradleyofkansas** [comment]
+1

**Pull request merged**
