### PR TITLE
Consolidated Records for Exlamation and Question Mark

### PR DESCRIPTION
**Pull request by Slothjams**
* Icon Updated: src/icons/0037_exclamation_i_lightCircleGray.svg
* Icon Updated: src/icons/0037_exclamation_i_heavyDiamondRed.svg
* Icon Updated: src/icons/0061_questionMark_i_diamond_light.svg
* Icon Updated: src/icons/0061_questionMark_a.svg,themeable

### CODE REVIEW

**Comment by sethbroox** [comment]
James, I see changes made to the following items:

- notMet,src/icons/0041_x_i_heavyCircle.svg,themeable

- list,src/icons/0075_list_a.svg,themeable

I am unsure what these changes have to do with the items listed in the change log.

**Comment by Slothjams** [comment]
Added notMet and List back in. Sometimes Excel can be problematic when entering
new rows and deletes others.

**Comment by bradleyofkansas** [comment]
@sethbroox no one is waiting on this, so we are ok, but I don't have permissions to 'publish' or accept the pull request.  I'll follow up with Brett on that.  If you look to the bottom right, I'm not listed as a 'participant'

**Comment by Slothjams** [comment]
@sethbroox Could I get you to commit this pull req? I have a couple other icons that need to be added to the repo

**Comment by Slothjams** [comment]
@sethbroox Updated the duplicate aliases to:
Unspecified > Unexpected
Help > Question

**Comment by sethbroox** [comment]
+1

**Pull request merged**
